apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: hello-ingress
 annotations:
   kubernetes.io/ingress.class: kong
spec:
 rules:
 - http:
     paths:
     - path: /taskproducer
       pathType: Prefix
       backend:
         service:
           name: producer
           port:
             number: 80
     - path: /taskprocessor
       pathType: Prefix
       backend:
         service:
           name: taskprocessor
           port:
             number: 80


---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: twelve-per-min
config:
 minute: 12
 policy: local
plugin: rate-limiting
